baseurl: "/shopebusiness-blog"
url: "https://shamsishakeeb.github.io"
title: "Shop-E-Business Blog"
description: "E-commerce tips, tutorials, and updates."
theme: jekyll-theme-minimal
permalink: /:title/
plugins:
  - jekyll-sitemap